version: '2'
services:

  frontend:
    image: mhart/alpine-node:latest
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3000"
    links:
      - backend
    volumes:
      - ../app-example/client/:/app

  backend:
    image: mhart/alpine-node:latest
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "8080"
    volumes:
      - ../app-example/server/:/app

  nginx:
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
    volumes:
      - ../ssl/:/opt/nginx/ssl
